import type { Theme } from "@skeletonlabs/skeleton/themes"

const wasp = {
	name: "wasp",
	properties: {
		"--type-scale-factor": "1.25",
		"--type-scale-1": "calc(0.75rem * var(--type-scale-factor))",
		"--type-scale-2": "calc(0.875rem * var(--type-scale-factor))",
		"--type-scale-3": "calc(1rem * var(--type-scale-factor))",
		"--type-scale-4": "calc(1.125rem * var(--type-scale-factor))",
		"--type-scale-5": "calc(1.25rem * var(--type-scale-factor))",
		"--type-scale-6": "calc(1.5rem * var(--type-scale-factor))",
		"--type-scale-7": "calc(1.875rem * var(--type-scale-factor))",
		"--type-scale-8": "calc(2.25rem * var(--type-scale-factor))",
		"--type-scale-9": "calc(3rem * var(--type-scale-factor))",
		"--type-scale-10": "calc(3.75rem * var(--type-scale-factor))",
		"--type-scale-11": "calc(4.5rem * var(--type-scale-factor))",
		"--type-scale-12": "calc(6rem * var(--type-scale-factor))",
		"--type-scale-13": "calc(8rem * var(--type-scale-factor))",
		"--base-font-color": "var(--color-surface-950)",
		"--base-font-color-dark": "var(--color-surface-50)",
		"--base-font-family":
			"ui-monospace, Cascadia Code, Source Code Pro, Menlo, Consolas, DejaVu Sans Mono, monospace",
		"--base-font-size": "inherit",
		"--base-line-height": "inherit",
		"--base-font-weight": "normal",
		"--base-font-style": "normal",
		"--base-letter-spacing": "0em",
		"--heading-font-color": "inherit",
		"--heading-font-color-dark": "inherit",
		"--heading-font-family": "inherit",
		"--heading-font-weight": "bold",
		"--heading-font-style": "normal",
		"--heading-letter-spacing": "inherit",
		"--anchor-font-color": "var(--color-primary-500)",
		"--anchor-font-color-dark": "var(--color-primary-500)",
		"--anchor-font-family": "inherit",
		"--anchor-font-size": "inherit",
		"--anchor-line-height": "inherit",
		"--anchor-font-weight": "inherit",
		"--anchor-font-style": "inherit",
		"--anchor-letter-spacing": "inherit",
		"--anchor-text-decoration": "none",
		"--anchor-text-decoration-hover": "underline",
		"--anchor-text-decoration-active": "none",
		"--anchor-text-decoration-focus": "none",
		"--space-scale-factor": "1",
		"--radii-default": "6px",
		"--radii-container": "12px",
		"--border-width-default": "2px",
		"--divide-width-default": "1px",
		"--outline-width-default": "1px",
		"--ring-width-default": "1px",
		"--body-background-color": "var(--color-surface-50)",
		"--body-background-color-dark": "var(--color-surface-950)",
		"--color-primary-50": "255 234 204",
		"--color-primary-100": "255 212 163",
		"--color-primary-200": "255 190 122",
		"--color-primary-300": "255 167 82",
		"--color-primary-400": "255 145 41",
		"--color-primary-500": "255 123 0",
		"--color-primary-600": "212 103 0",
		"--color-primary-700": "169 83 0",
		"--color-primary-800": "127 62 0",
		"--color-primary-900": "84 42 0",
		"--color-primary-950": "41 22 0",
		"--color-primary-contrast-dark": "var(--color-primary-950)",
		"--color-primary-contrast-light": "var(--color-primary-50)",
		"--color-primary-contrast-50": "var(--color-primary-contrast-dark)",
		"--color-primary-contrast-100": "var(--color-primary-contrast-dark)",
		"--color-primary-contrast-200": "var(--color-primary-contrast-dark)",
		"--color-primary-contrast-300": "var(--color-primary-contrast-dark)",
		"--color-primary-contrast-400": "var(--color-primary-contrast-dark)",
		"--color-primary-contrast-500": "var(--color-primary-contrast-dark)",
		"--color-primary-contrast-600": "var(--color-primary-contrast-dark)",
		"--color-primary-contrast-700": "var(--color-primary-contrast-light)",
		"--color-primary-contrast-800": "var(--color-primary-contrast-light)",
		"--color-primary-contrast-900": "var(--color-primary-contrast-light)",
		"--color-primary-contrast-950": "var(--color-primary-contrast-light)",
		"--color-secondary-50": "254 242 225",
		"--color-secondary-100": "254 226 180",
		"--color-secondary-200": "254 210 135",
		"--color-secondary-300": "255 194 90",
		"--color-secondary-400": "255 178 45",
		"--color-secondary-500": "255 162 0",
		"--color-secondary-600": "216 139 0",
		"--color-secondary-700": "177 116 0",
		"--color-secondary-800": "139 94 0",
		"--color-secondary-900": "100 71 0",
		"--color-secondary-950": "61 48 0",
		"--color-secondary-contrast-dark": "var(--color-secondary-950)",
		"--color-secondary-contrast-light": "var(--color-secondary-50)",
		"--color-secondary-contrast-50": "var(--color-secondary-contrast-dark)",
		"--color-secondary-contrast-100": "var(--color-secondary-contrast-dark)",
		"--color-secondary-contrast-200": "var(--color-secondary-contrast-dark)",
		"--color-secondary-contrast-300": "var(--color-secondary-contrast-dark)",
		"--color-secondary-contrast-400": "var(--color-secondary-contrast-dark)",
		"--color-secondary-contrast-500": "var(--color-secondary-contrast-dark)",
		"--color-secondary-contrast-600": "var(--color-secondary-contrast-dark)",
		"--color-secondary-contrast-700": "var(--color-secondary-contrast-light)",
		"--color-secondary-contrast-800": "var(--color-secondary-contrast-light)",
		"--color-secondary-contrast-900": "var(--color-secondary-contrast-light)",
		"--color-secondary-contrast-950": "var(--color-secondary-contrast-light)",
		"--color-tertiary-50": "254 254 215",
		"--color-tertiary-100": "254 244 172",
		"--color-tertiary-200": "254 234 129",
		"--color-tertiary-300": "255 224 86",
		"--color-tertiary-400": "255 214 43",
		"--color-tertiary-500": "255 204 0",
		"--color-tertiary-600": "218 176 0",
		"--color-tertiary-700": "181 147 0",
		"--color-tertiary-800": "145 119 0",
		"--color-tertiary-900": "108 90 0",
		"--color-tertiary-950": "71 62 0",
		"--color-tertiary-contrast-dark": "var(--color-tertiary-950)",
		"--color-tertiary-contrast-light": "var(--color-tertiary-50)",
		"--color-tertiary-contrast-50": "var(--color-tertiary-contrast-dark)",
		"--color-tertiary-contrast-100": "var(--color-tertiary-contrast-dark)",
		"--color-tertiary-contrast-200": "var(--color-tertiary-contrast-dark)",
		"--color-tertiary-contrast-300": "var(--color-tertiary-contrast-dark)",
		"--color-tertiary-contrast-400": "var(--color-tertiary-contrast-dark)",
		"--color-tertiary-contrast-500": "var(--color-tertiary-contrast-dark)",
		"--color-tertiary-contrast-600": "var(--color-tertiary-contrast-dark)",
		"--color-tertiary-contrast-700": "var(--color-tertiary-contrast-dark)",
		"--color-tertiary-contrast-800": "var(--color-tertiary-contrast-light)",
		"--color-tertiary-contrast-900": "var(--color-tertiary-contrast-light)",
		"--color-tertiary-contrast-950": "var(--color-tertiary-contrast-light)",
		"--color-success-50": "228 255 189",
		"--color-success-100": "213 255 151",
		"--color-success-200": "198 255 113",
		"--color-success-300": "183 255 76",
		"--color-success-400": "168 255 38",
		"--color-success-500": "153 255 0",
		"--color-success-600": "127 213 0",
		"--color-success-700": "100 171 0",
		"--color-success-800": "74 130 0",
		"--color-success-900": "47 88 0",
		"--color-success-950": "21 46 0",
		"--color-success-contrast-dark": "var(--color-success-950)",
		"--color-success-contrast-light": "var(--color-success-50)",
		"--color-success-contrast-50": "var(--color-success-contrast-dark)",
		"--color-success-contrast-100": "var(--color-success-contrast-dark)",
		"--color-success-contrast-200": "var(--color-success-contrast-dark)",
		"--color-success-contrast-300": "var(--color-success-contrast-dark)",
		"--color-success-contrast-400": "var(--color-success-contrast-dark)",
		"--color-success-contrast-500": "var(--color-success-contrast-dark)",
		"--color-success-contrast-600": "var(--color-success-contrast-dark)",
		"--color-success-contrast-700": "var(--color-success-contrast-dark)",
		"--color-success-contrast-800": "var(--color-success-contrast-light)",
		"--color-success-contrast-900": "var(--color-success-contrast-light)",
		"--color-success-contrast-950": "var(--color-success-contrast-light)",
		"--color-warning-50": "180 254 232",
		"--color-warning-100": "157 254 236",
		"--color-warning-200": "134 254 240",
		"--color-warning-300": "112 255 244",
		"--color-warning-400": "89 255 248",
		"--color-warning-500": "66 255 252",
		"--color-warning-600": "53 210 212",
		"--color-warning-700": "40 165 172",
		"--color-warning-800": "26 119 131",
		"--color-warning-900": "13 74 91",
		"--color-warning-950": "0 29 51",
		"--color-warning-contrast-dark": "var(--color-warning-950)",
		"--color-warning-contrast-light": "var(--color-warning-50)",
		"--color-warning-contrast-50": "var(--color-warning-contrast-dark)",
		"--color-warning-contrast-100": "var(--color-warning-contrast-dark)",
		"--color-warning-contrast-200": "var(--color-warning-contrast-dark)",
		"--color-warning-contrast-300": "var(--color-warning-contrast-dark)",
		"--color-warning-contrast-400": "var(--color-warning-contrast-dark)",
		"--color-warning-contrast-500": "var(--color-warning-contrast-dark)",
		"--color-warning-contrast-600": "var(--color-warning-contrast-dark)",
		"--color-warning-contrast-700": "var(--color-warning-contrast-dark)",
		"--color-warning-contrast-800": "var(--color-warning-contrast-light)",
		"--color-warning-contrast-900": "var(--color-warning-contrast-light)",
		"--color-warning-contrast-950": "var(--color-warning-contrast-light)",
		"--color-error-50": "255 214 216",
		"--color-error-100": "255 181 183",
		"--color-error-200": "255 149 150",
		"--color-error-300": "255 116 117",
		"--color-error-400": "255 84 84",
		"--color-error-500": "255 51 51",
		"--color-error-600": "219 41 41",
		"--color-error-700": "183 31 31",
		"--color-error-800": "147 21 21",
		"--color-error-900": "111 11 11",
		"--color-error-950": "75 1 1",
		"--color-error-contrast-dark": "0 0 0",
		"--color-error-contrast-light": "255 255 255",
		"--color-error-contrast-50": "var(--color-error-contrast-dark)",
		"--color-error-contrast-100": "var(--color-error-contrast-dark)",
		"--color-error-contrast-200": "var(--color-error-contrast-dark)",
		"--color-error-contrast-300": "var(--color-error-contrast-dark)",
		"--color-error-contrast-400": "var(--color-error-contrast-dark)",
		"--color-error-contrast-500": "var(--color-error-contrast-dark)",
		"--color-error-contrast-600": "var(--color-error-contrast-light)",
		"--color-error-contrast-700": "var(--color-error-contrast-light)",
		"--color-error-contrast-800": "var(--color-error-contrast-light)",
		"--color-error-contrast-900": "var(--color-error-contrast-light)",
		"--color-error-contrast-950": "var(--color-error-contrast-light)",
		"--color-surface-50": "255 252 240",
		"--color-surface-100": "216 213 203",
		"--color-surface-200": "177 175 166",
		"--color-surface-300": "139 136 130",
		"--color-surface-400": "100 98 93",
		"--color-surface-500": "61 59 56",
		"--color-surface-600": "52 51 48",
		"--color-surface-700": "44 43 40",
		"--color-surface-800": "35 34 33",
		"--color-surface-900": "27 26 25",
		"--color-surface-950": "18 18 17",
		"--color-surface-contrast-dark": "var(--color-surface-950)",
		"--color-surface-contrast-light": "var(--color-surface-50)",
		"--color-surface-contrast-50": "var(--color-surface-contrast-dark)",
		"--color-surface-contrast-100": "var(--color-surface-contrast-dark)",
		"--color-surface-contrast-200": "var(--color-surface-contrast-dark)",
		"--color-surface-contrast-300": "var(--color-surface-contrast-dark)",
		"--color-surface-contrast-400": "var(--color-surface-contrast-light)",
		"--color-surface-contrast-500": "var(--color-surface-contrast-light)",
		"--color-surface-contrast-600": "var(--color-surface-contrast-light)",
		"--color-surface-contrast-700": "var(--color-surface-contrast-light)",
		"--color-surface-contrast-800": "var(--color-surface-contrast-light)",
		"--color-surface-contrast-900": "var(--color-surface-contrast-light)",
		"--color-surface-contrast-950": "var(--color-surface-contrast-light)"
	},
	metadata: {
		version: "3.0.0"
	}
} satisfies Theme

export default wasp
