name: Version
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: rguillaume/discord-action-embed@v1.0.4
        with:
          webhook: ${{ secrets.UPDATES_WEBHOOK }}
          embed: '{"title": "Update: ${{ github.event.repository.name }}", "description": ${{ toJSON(github.event.head_commit.message) }}, "footer": {"text": "Committer: ${{ github.event.head_commit.author.username }}"}, "color": "16777215"}'